[package]
name = "human-resources-office"
version = "0.1.0"
description = "accounts.txt 기반 접속 대상 관리 프로그램"
authors = ["mini_yeoreum"]
edition = "2021"

[lib]
name = "human_resources_office_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
keyring = "4.2.0"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
url = "2"
